package gregtech.common.metatileentities.multi.electric.generator;

public class LargeFusionComputer {
    public static final String[] L0 = { "                                               ",
            "                                               ", "                    FCCCCCF                    ",
            "                    FCIBICF                    ", "                    FCCCCCF                    ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "  FFF                                     FFF  ",
            "  CCC                                     CCC  ", "  CIC                                     CIC  ",
            "  CBC                                     CBC  ", "  CIC                                     CIC  ",
            "  CCC                                     CCC  ", "  FFF                                     FFF  ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                                               ",
            "                                               ", "                    FCCCCCF                    ",
            "                    FCIBICF                    ", "                    FCCCCCF                    ",
            "                                               ", "                                               ", };

    public static final String[] L1 = { "                                               ",
            "                    FCBBBCF                    ", "                   CC     CC                   ",
            "                CCCCC     CCCCC                ", "              CCCCCCC     CCCCCCC              ",
            "            CCCCCCC FCBBBCF CCCCCCC            ", "           CCCCC               CCCCC           ",
            "          CCCC                   CCCC          ", "         CCC                       CCC         ",
            "        CCC                         CCC        ", "       CCC                           CCC       ",
            "      CCC                             CCC      ", "     CCC                               CCC     ",
            "     CCC                               CCC     ", "    CCC                                 CCC    ",
            "    CCC                                 CCC    ", "   CCC                                   CCC   ",
            "   CCC                                   CCC   ", "   CCC                                   CCC   ",
            "  CCC                                     CCC  ", " FCCCF                                   FCCCF ",
            " C   C                                   C   C ", " B   B                                   B   B ",
            " B   B                                   B   B ", " B   B                                   B   B ",
            " C   C                                   C   C ", " FCCCF                                   FCCCF ",
            "  CCC                                     CCC  ", "   CCC                                   CCC   ",
            "   CCC                                   CCC   ", "   CCC                                   CCC   ",
            "    CCC                                 CCC    ", "    CCC                                 CCC    ",
            "     CCC                               CCC     ", "     CCC                               CCC     ",
            "      CCC                             CCC      ", "       CCC                           CCC       ",
            "        CCC                         CCC        ", "         CCC                       CCC         ",
            "          CCCC                   CCCC          ", "           CCCCC               CCCCC           ",
            "            CCCCCCC FCBBBCF CCCCCCC            ", "              CCCCCCC     CCCCCCC              ",
            "                CCCCC     CCCCC                ", "                   CC     CC                   ",
            "                    FCBBBCF                    ", "                                               ", };

    public static final String[] L2 = { "                    FCCCCCF                    ",
            "                   CC     CC                   ", "                CCCCC     CCCCC                ",
            "              CCCCCHHHHHHHHHCCCCC              ", "            CCCCHHHCC     CCHHHCCCC            ",
            "           CCCHHCCCCC     CCCCCHHCCC           ", "          ECHHCCCCC FCCCCCF CCCCCHHCE          ",
            "         CCHCCCC               CCCCHCC         ", "        CCHCCC                   CCCHCC        ",
            "       CCHCE                       ECHCC       ", "      ECHCC                         CCHCE      ",
            "     CCHCE                           ECHCC     ", "    CCHCC                             CCHCC    ",
            "    CCHCC                             CCHCC    ", "   CCHCC                               CCHCC   ",
            "   CCHCC                               CCHCC   ", "  CCHCC                                 CCHCC  ",
            "  CCHCC                                 CCHCC  ", "  CCHCC                                 CCHCC  ",
            " CCHCC                                   CCHCC ", "FCCHCCF                                 FCCHCCF",
            "C  H  C                                 C  H  C", "C  H  C                                 C  H  C",
            "C  H  C                                 C  H  C", "C  H  C                                 C  H  C",
            "C  H  C                                 C  H  C", "FCCHCCF                                 FCCHCCF",
            " CCHCC                                   CCHCC ", "  CCHCC                                 CCHCC  ",
            "  CCHCC                                 CCHCC  ", "  CCHCC                                 CCHCC  ",
            "   CCHCC                               CCHCC   ", "   CCHCC                               CCHCC   ",
            "    CCHCC                             CCHCC    ", "    CCHCC                             CCHCC    ",
            "     CCHCE                           ECHCC     ", "      ECHCC                         CCHCE      ",
            "       CCHCE                       ECHCC       ", "        CCHCCC                   CCCHCC        ",
            "         CCHCCCC               CCCCHCC         ", "          ECHHCCCCC FCCCCCF CCCCCHHCE          ",
            "           CCCHHCCCCC     CCCCCHHCCC           ", "            CCCCHHHCC     CCHHHCCCC            ",
            "              CCCCCHHHHHHHHHCCCCC              ", "                CCCCC     CCCCC                ",
            "                   CC     CC                   ", "                    FCCCCCF                    ", };

    public static final String[] L3 = { "                    FCIBICF                    ",
            "                   CC     CC                   ", "                CCCHHHHHHHHHCCC                ",
            "              CCHHHHHHHHHHHHHHHCC              ", "            CCHHHHHHHHHHHHHHHHHHHCC            ",
            "           CHHHHHHHCC     CCHHHHHHHC           ", "          CHHHHHCCC FCIBICF CCCHHHHHC          ",
            "         CHHHHCC               CCHHHHC         ", "        CHHHCC                   CCHHHC        ",
            "       CHHHC                       CHHHC       ", "      CHHHC                         CHHHC      ",
            "     CHHHC                           CHHHC     ", "    CHHHC                             CHHHC    ",
            "    CHHHC                             CHHHC    ", "   CHHHC                               CHHHC   ",
            "   CHHHC                               CHHHC   ", "  CHHHC                                 CHHHC  ",
            "  CHHHC                                 CHHHC  ", "  CHHHC                                 CHHHC  ",
            " CHHHC                                   CHHHC ", "FCHHHCF                                 FCHHHCF",
            "C HHH C                                 C HHH C", "I HHH I                                 I HHH I",
            "B HHH B                                 B HHH B", "I HHH I                                 I HHH I",
            "C HHH C                                 C HHH C", "FCHHHCF                                 FCHHHCF",
            " CHHHC                                   CHHHC ", "  CHHHC                                 CHHHC  ",
            "  CHHHC                                 CHHHC  ", "  CHHHC                                 CHHHC  ",
            "   CHHHC                               CHHHC   ", "   CHHHC                               CHHHC   ",
            "    CHHHC                             CHHHC    ", "    CHHHC                             CHHHC    ",
            "     CHHHC                           CHHHC     ", "      CHHHC                         CHHHC      ",
            "       CHHHC                       CHHHC       ", "        CHHHCC                   CCHHHC        ",
            "         CHHHHCC               CCHHHHC         ", "          CHHHHHCCC FCI~ICF CCCHHHHHC          ",
            "           CHHHHHHHCC     CCHHHHHHHC           ", "            CCHHHHHHHHHHHHHHHHHHHCC            ",
            "              CCHHHHHHHHHHHHHHHCC              ", "                CCCHHHHHHHHHCCC                ",
            "                   CC     CC                   ", "                    FCIBICF                    ", };
}
